#!/bin/sh

# Wait for cloud-init to finish
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done

# Install necessary packages
yum -y install httpd php unzip wget

# Ensure the network is online before proceeding
while ! ping -c1 google.com &>/dev/null; do echo "Waiting for network..."; sleep 1; done

# Enable and start Apache
systemctl enable httpd
systemctl start httpd

# Navigate to the /tmp directory
cd /tmp

# Download the ZIP file
wget https://techu-poc-challenge.s3.amazonaws.com/hawa-poc/examplefiles-as.zip

# Unzip the contents directly into the Apache document root
unzip examplefiles-as.zip -d /var/www/html/

# Set the correct permissions
chmod -R 755 /var/www/html/
chown -R apache:apache /var/www/html/

# Restart Apache to apply changes
systemctl restart httpd
